### I**ntroduction to the Tensor**

### **`torch.tensor()`**

In [54]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


#### 1. Scalar

In [55]:
scalar = torch.tensor(5)

print(scalar)
print(type(scalar))
print(scalar.ndim)  # Attribute used in NumPy
print(scalar.dim()) # Method used in PyTorch
print(scalar.item())

tensor(5)
<class 'torch.Tensor'>
0
0
5


#### 2. Vector

In [56]:
vector = torch.tensor([5, 5])

print(vector)
print(vector.dim())
print(vector.shape)

tensor([5, 5])
1
torch.Size([2])


#### 3. Matrix

In [57]:
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])

print(MATRIX)
print(MATRIX.dim())
print(MATRIX.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


#### 4. Tensor

In [58]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print(TENSOR)
print(TENSOR.dim())
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


- `dim = 0`, which refers to the `columns` $\downarrow$

- `dim = 1`, which refers to the `rows` $\rightarrow$

![tensor](https://static.javatpoint.com/tutorial/pytorch/images/pytorch-tensors.png)


<br></br>

![tensor](https://editor.analyticsvidhya.com/uploads/64798tensor.png)

In [59]:
import torch

# 0-dimensional tensor (scalar)
scalar_tensor = torch.tensor(42)
print("Scalar tensor:", scalar_tensor)
print("Dimensions:", scalar_tensor.dim())

# 1-dimensional tensor (vector)
vector_tensor = torch.tensor([1, 2, 3, 4])
print("\nVector tensor:", vector_tensor)
print("Dimensions:", vector_tensor.dim())

# 2-dimensional tensor (matrix)
matrix_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("\nMatrix tensor:")
print(matrix_tensor)
print("Dimensions:", matrix_tensor.dim())

# 3-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D tensor:")
print(tensor_3d)
print("Dimensions:", tensor_3d.dim())

# 4-dimensional tensor
tensor_4d = torch.tensor([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\n4D tensor:")
print(tensor_4d)
print("Dimensions:", tensor_4d.dim())


Scalar tensor: tensor(42)
Dimensions: 0

Vector tensor: tensor([1, 2, 3, 4])
Dimensions: 1

Matrix tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Dimensions: 2

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimensions: 3

4D tensor:
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Dimensions: 4


### **`torch.rand()`**

In [60]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.2919, 0.4190, 0.4655],
        [0.2305, 0.5963, 0.9268],
        [0.6224, 0.0080, 0.2391]])

In [61]:
# Create an image tensor with similar shape to an image tensor
rand_img_tensor = torch.rand(size=(3, 224, 224)) # color channels, height, width

print(rand_img_tensor.ndim)
print(rand_img_tensor.shape)

3
torch.Size([3, 224, 224])


### `torch.zeros()` & `torch.ones()`



In [62]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### `torch.dtype()`

In [64]:
print(scalar.dtype)
print(vector.dtype)
print(MATRIX.dtype)
print(TENSOR.dtype)
print(zeros.dtype)
print(ones.dtype)

torch.int64
torch.int64
torch.int64
torch.int64
torch.float32
torch.float32


**Note:** The default data type for tensors in PyTorch is `torch.float32`

In [53]:
# Create a tensor with specified dtype
tensor_float16 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
tensor_float32 = torch.tensor([1.0, 2.0, 3.0])
tensor_float64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

print(tensor_float16.dtype)
print(tensor_float32.dtype)
print(tensor_float64.dtype)

torch.float16
torch.float32
torch.float64


### `torch.range(start=, end=, step=)`

In [67]:
torch.arange(start=1, end=11, step=1 )

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **`torch.squeeze()`**

Remove dimensions of size 1 from the shape of a tensor.

In [2]:
import torch

# Create the input tensor
input_tensor = torch.randn([32, 1, 28, 28], dtype=torch.float)

# Squeeze the tensor along dimension 0
squeezed_tensor = torch.squeeze(input_tensor, dim=0)

print("Original tensor shape:", input_tensor.shape)
print("Squeezed tensor shape:", squeezed_tensor.shape)


Original tensor shape: torch.Size([32, 1, 28, 28])
Squeezed tensor shape: torch.Size([32, 1, 28, 28])


In [3]:
import torch

# Create the input tensor
input_tensor = torch.randn([32, 1, 28, 28], dtype=torch.float)

# Squeeze the tensor along dimension 1
squeezed_tensor = torch.squeeze(input_tensor, dim=1)

print("Original tensor shape:", input_tensor.shape)
print("Squeezed tensor shape:", squeezed_tensor.shape)


Original tensor shape: torch.Size([32, 1, 28, 28])
Squeezed tensor shape: torch.Size([32, 28, 28])


In [4]:
import torch

x = torch.randn(1, 2, 3, 4)
squeezed_x = torch.squeeze(x, dim=0)
print(squeezed_x.shape)

torch.Size([2, 3, 4])


### **`torch.unsqueeze()`**

This function directly available in `TensorFlow`. However, in other frameworks like `PyTorch`, unsqueeze is used to add a dimension of size 1 at a specified axis. In `TensorFlow`, a similar effect can be achieved using `tf.expand_dims`.

**1. Grey Scale**

In [5]:
input_tensor = torch.randn([32, 1, 28, 28], dtype=torch.float)
print("Original size:", input_tensor.size())

first_tensor = input_tensor[0]
print("Size before unsqueeze: ",first_tensor.shape)

# unsqueeze_tensor_0 = torch.unsqueeze(x, 0)
unsqueeze_tensor_0 = first_tensor.unsqueeze(dim=0)
print("Size after unsqueeze at dim 0: ", unsqueeze_tensor_0.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_1 = first_tensor.unsqueeze(dim=1)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_1.size())

Original size: torch.Size([32, 1, 28, 28])
Size before unsqueeze:  torch.Size([1, 28, 28])
Size after unsqueeze at dim 0:  torch.Size([1, 1, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([1, 1, 28, 28])


The bottom two results are the same because both are adding a single batch dimension to a single-channel image. If first_tensor had more than one channel, the results of unsqueezing at different dimensions would be different. For example, if first_tensor was `[3, 28, 28]` (representing an `RGB` image), unsqueezing at dim 0 would result in `[1, 3, 28, 28]`, while unsqueezing at dim 1 would result in `[3, 1, 28, 28]`

**Note:** `unsqueeze_tensor_2 = x.unsqueeze(2)`

- This will raise an IndexError as we are attemptting to unsqueeze the tensor at a dimension index that doesn’t exist for the given tensor.

**2. RGB**

In [6]:
# Example: Unsqueeze a tensor
input_tensor = torch.randn([32, 3, 28, 28], dtype=torch.float)
print("Original batch size:", input_tensor.size())

first_tensor = input_tensor[0]
print("Size before unsqueeze: ", first_tensor.shape)

# unsqueeze_tensor_0 = torch.unsqueeze(x, 0)
unsqueeze_tensor_0 = first_tensor.unsqueeze(dim=0)
print("Size after unsqueeze at dim 0: ", unsqueeze_tensor_0.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_1 = first_tensor.unsqueeze(dim=1)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_1.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_2 = first_tensor.unsqueeze(dim=2)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_2.size())

Original batch size: torch.Size([32, 3, 28, 28])
Size before unsqueeze:  torch.Size([3, 28, 28])
Size after unsqueeze at dim 0:  torch.Size([1, 3, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([3, 1, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([3, 28, 1, 28])


### `argmax()`

- To get the indices of the maximum values

In [7]:
import torch

# Simulated output scores from a neural network for 3 classes (cat, dog, bird)
y_pred = torch.tensor([[1.2, 0.9, 0.3, 0.4],
                       [0.2, 2.1, 1.8, 3.1],
                       [0.1, 1.5, 2.2, 2.1]])

# Applying argmax to get the indices of the maximum values along dimension
predicted_classes_0 = torch.argmax(y_pred, dim=0) # Applies argmax along dimension 0, which refers to the columns
predicted_classes_1 = torch.argmax(y_pred, dim=1) # Applies argmax along dimension 1, referring to the rows

print(predicted_classes_0)
print(predicted_classes_1)

tensor([0, 1, 2, 1])
tensor([0, 3, 2])


### **`torch.cat()`**

- Concatenating tensors along a specified dimension.

In [8]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Concatenate along dimension 0 (rows)
concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)
print("Concatenated tensor along dimension 0:\n", concatenated_tensor)

# Concatenate along dimension 1 (columns)
concatenated_tensor_dim1 = torch.cat((tensor1, tensor2), dim=1)
print("Concatenated tensor along dimension 1:\n", concatenated_tensor_dim1)

Concatenated tensor along dimension 0:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenated tensor along dimension 1:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### **`torch.flatten()`**

In [9]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Assuming concatenated_tensor_dim1 is already defined from the previous example
concatenated_tensor_dim0 = torch.cat((tensor1, tensor2), dim=0)
concatenated_tensor_dim1 = torch.cat((tensor1, tensor2), dim=1)

# Flatten the concatenated tensor
flat_tensor0 = torch.flatten(concatenated_tensor_dim0)
flat_tensor1 = torch.flatten(concatenated_tensor_dim1)

print("Flattened tensor 0:\n", flat_tensor0)
print("Flattened tensor 1:\n", flat_tensor1)

Flattened tensor 0:
 tensor([1, 2, 3, 4, 5, 6, 7, 8])
Flattened tensor 1:
 tensor([1, 2, 5, 6, 3, 4, 7, 8])


### **`torch.stack()`**

In [10]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Stack tensors along a new dimension (dimension 0)
stacked_tensor0 = torch.stack((tensor1, tensor2), dim=0)
stacked_tensor1 = torch.stack((tensor1, tensor2), dim=1)

print("Stacked tensor along dimension 0:\n", stacked_tensor0)
print("\n")
print("Stacked tensor along dimension 1:\n", stacked_tensor1)

Stacked tensor along dimension 0:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Stacked tensor along dimension 1:
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


### `torch.isclose()` & `torch.eq()`

In [11]:
import torch

# Define two tensors
tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([1.1, 2.2, 3.3])

# Check if the tensors are close within a tolerance of 0.2
close_tensors = torch.isclose(tensor1, tensor2, atol=0.2)

print(close_tensors)

tensor([ True,  True, False])


In [12]:
import torch

# Define two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([1, 2, 4])

# Check for exact equality
equal_tensors = torch.eq(tensor1, tensor2)

print(equal_tensors)

tensor([ True,  True, False])


>NOTE: Unlike `torch.isclose`, `torch.eq` does not have a `tolerance` parameter because it strictly checks for exact equality. It's useful when you need to perform element-wise comparisons where exact matches are required.

In [13]:
import torch

# Define two tensors
tensor1 = torch.tensor([1.001, 2.002, 3.003])
tensor2 = torch.tensor([1.0, 2.0, 3.0])

# Check for approximate equality with tolerance
close_tensors = torch.isclose(tensor1, tensor2, atol=0.01)

# Check for exact equality
equal_tensors = torch.eq(tensor1, tensor2)

print("Approximate equality with tolerance:")
print(close_tensors)

print("\nExact equality:")
print(equal_tensors)


Approximate equality with tolerance:
tensor([True, True, True])

Exact equality:
tensor([False, False, False])
