### **Precision in Computing**

It refers to the level of detail or exactness in representing numerical values.

It determines how accurately a number is stored and manipulated within a computer system. **Precision** is often characterized by the number of digits used to represent a value.

Higher precision allows for more detailed and accurate representation, reducing rounding errors and enhancing calculations.

For example:

- `Single precision`: Typically uses `32 bits` to represent a floating-point number, offering about `7` decimal digits of accuracy.

- `Double precision`: Uses `64 bits`, providing about `15-16` decimal digits of accuracy.

Precision is crucial in applications requiring high accuracy, such as scientific computations, graphics, and financial modeling.

## **Tensor datatypes**

Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

- Tensors not right `datatype`.
- Tensors not right `shape`.
- Tensors not on the right `device`.

In [1]:
import torch

In [2]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # what datatype is the tensor (e.g. float32 or float16)
                               device=None,         # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations

print(float_32_tensor.shape)
print(float_32_tensor.ndim)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
1
torch.float32
cpu


In [3]:
float_16_tensor = float_32_tensor.type(torch.float16)

print(float_16_tensor.dtype)

torch.float16


In [4]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In PyTorch, torch.long is a data type representing `64-bit` integer (or `int64`). It is used when you need to store and manipulate integer values that require a larger range than `32-bit` integers can provide. Common use cases include:

- Indexing tensors
- Storing large integer values
- Handling operations where 32-bit integers might overflow

Using `torch.long` ensures that computations involving large integers are accurate and do not result in overflow errors.

In [5]:
import torch

# Create a tensor with float32 type
float32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
print("Original tensor:", float32_tensor)
print("Original tensor dtype:", float32_tensor.dtype)

# Convert the float32 tensor to int64 (torch.long) type
int64_tensor = float32_tensor.to(torch.long)
print("Converted tensor:", int64_tensor)
print("Converted tensor dtype:", int64_tensor.dtype)

Original tensor: tensor([3., 6., 9.])
Original tensor dtype: torch.float32
Converted tensor: tensor([3, 6, 9])
Converted tensor dtype: torch.int64


Manipulating Tensors (tensor operations)
Tensor opertions include:

- `Addition`
- `Subtraction`
- `Multiplication` (element-wise)
- `Division`
- `Matrix multiplication`

In [6]:
tensor = torch.tensor([1, 2, 3])

print(tensor+10)
print(tensor-10)
print(tensor*10)
print(tensor/10)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


**PyTorch in-built functions**

In [7]:
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### **Matrix multiplication**

Two main ways of performing multiplication in neural networks and deep learning:

- **Element-wise multiplication**
- **Matrix mutliplication** (`dot product`)

The inner dimensions must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work

The resulting matrix has the shape of the outer dimensions:

- `(2, 3) @ (3, 2) -> (2, 2)`
- `(3, 2) @ (2, 3) -> (3, 3)`

In [8]:
print(tensor*tensor)
print(torch.mul(tensor, tensor))

tensor([1, 4, 9])
tensor([1, 4, 9])


In [9]:
%%time

tensor = torch.tensor([1, 2, 3])

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.73 ms, sys: 0 ns, total: 1.73 ms
Wall time: 1.84 ms


In [10]:
# Faster due to optimized PyTorch operation.
%%time
torch.mul(tensor, tensor)

CPU times: user 28 µs, sys: 6 µs, total: 34 µs
Wall time: 36.5 µs


tensor([1, 4, 9])

In [11]:
import torch
from timeit import default_timer as timer

# Function to time the first snippet (for loop)
def time_for_loop():
    tensor = torch.tensor([1, 2, 3])
    value = 0
    start_time = timer()
    for i in range(len(tensor)):
        value += tensor[i] * tensor[i]
    end_time = timer()
    elapsed_time = end_time - start_time
    print(f"Result of for loop: {value}")
    print(f"Time taken by for loop: {elapsed_time:.8f} seconds")
    return elapsed_time

# Function to time the second snippet (torch.mul)
def time_torch_mul():
    tensor = torch.tensor([1, 2, 3])
    start_time = timer()
    result = torch.mul(tensor, tensor)
    end_time = timer()
    elapsed_time = end_time - start_time
    print(f"Result of torch.mul: {result}")
    print(f"Time taken by torch.mul: {elapsed_time:.8f} seconds")
    return elapsed_time

# Time both snippets
time_for_loop_elapsed = time_for_loop()
time_torch_mul_elapsed = time_torch_mul()

# Compare and print which is faster
if time_for_loop_elapsed < time_torch_mul_elapsed:
    print(f"For loop is faster by {time_torch_mul_elapsed - time_for_loop_elapsed:.8f} seconds.")
else:
    print(f"torch.mul is faster by {time_for_loop_elapsed - time_torch_mul_elapsed:.8f} seconds.")


Result of for loop: 14
Time taken by for loop: 0.00010150 seconds
Result of torch.mul: tensor([1, 4, 9])
Time taken by torch.mul: 0.00001485 seconds
torch.mul is faster by 0.00008665 seconds.


`matmal()`

In [12]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.matmul(tensor_A, tensor_B)   # RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
result = torch.matmul(tensor_A, tensor_B.T)  # Transpose tensor_B before multiplication
print(tensor_A.shape, tensor_B.shape)
print(result)
print(result.shape)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])


### Finding the `min`, `max`, `mean`, `sum`, etc (tensor aggregation)

In [13]:
import torch

# Create a tensor using torch.arange
# tensor = torch.randn(3, 3)
tensor = torch.arange(1, 10, 1).reshape(3, 3).to(torch.float32)
print("Original Tensor:")
print(tensor)

# Finding the minimum value
min_value = torch.min(tensor)
print("\nMinimum Value:")
print(min_value.item())

# Finding the maximum value
max_value = torch.max(tensor)
print("\nMaximum Value:")
print(max_value.item())

# Finding the mean
mean_value = torch.mean(tensor)
print("\nMean Value:")
print(mean_value.item())

# Finding the sum
sum_value = torch.sum(tensor)
print("\nSum Value:")
print(sum_value.item())

# Finding the indices of the minimum and maximum values
min_indices = torch.argmin(tensor)
max_indices = torch.argmax(tensor)
print("\nIndices of Minimum and Maximum Values:")
print("Index of Minimum:", min_indices.item())
print("Index of Maximum:", max_indices.item())

Original Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Minimum Value:
1.0

Maximum Value:
9.0

Mean Value:
5.0

Sum Value:
45.0

Indices of Minimum and Maximum Values:
Index of Minimum: 0
Index of Maximum: 8


### **Reshaping, stacking, squeezing and unsqueezing tensors**

In [14]:
import torch

# Create a tensor using torch.arange
tensor = torch.arange(1, 13).reshape(3, 4)
print("Original Tensor:")
print(tensor)

# Reshape the tensor
reshaped_tensor = tensor.reshape(2, 6)
print("\nReshaped Tensor (2x6):")
print(reshaped_tensor)

# Stack tensors along a new dimension
tensor_A = torch.arange(1, 5).reshape(2, 2)
tensor_B = torch.arange(5, 9).reshape(2, 2)
stacked_tensor = torch.stack((tensor_A, tensor_B), dim=0)
print("\nStacked Tensor along dimension 0:")
print(stacked_tensor)

# Squeeze the tensor to remove single-dimensional entries
unsqueeze_tensor = torch.unsqueeze(tensor, dim=0)
print("\nUnsqueezed Tensor:")
print(unsqueeze_tensor.shape)  # Note the shape change after unsqueezing

# Unsqueeze the tensor to add a single-dimensional entry
squeezed_tensor = torch.squeeze(unsqueeze_tensor, dim=0)
print("\nSqueezed Tensor:")
print(squeezed_tensor.shape)  # Note the shape change after squeezing

Original Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reshaped Tensor (2x6):
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Stacked Tensor along dimension 0:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Unsqueezed Tensor:
torch.Size([1, 3, 4])

Squeezed Tensor:
torch.Size([3, 4])


In [15]:
x = torch.arange(1., 10.)
print(x, x.shape)

x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed_0 = x_squeezed.unsqueeze(dim=0)
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)

print(f"\nNew tensor: {x_unsqueezed_0}")
print(f"New shape: {x_unsqueezed_0.shape}")

print(f"\nNew tensor: {x_unsqueezed_1}")
print(f"New shape: {x_unsqueezed_1.shape}")

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


### `dim=0`, `dim=1`

In [16]:
import torch

tensor_A = torch.tensor([[1, 2], [3, 4]])
tensor_B = torch.tensor([[5, 6]])

print(tensor_A.shape, tensor_B.shape)
print(tensor_A.ndim, tensor_B.ndim)

# Concatenate tensor_B as a new row to tensor_A
concatenated_tensor = torch.cat((tensor_A, tensor_B), dim=0)
print(concatenated_tensor)

torch.Size([2, 2]) torch.Size([1, 2])
2 2
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [17]:
import torch

tensor_A = torch.tensor([[1, 2], [3, 4]])
tensor_B = torch.tensor([[5], [6]])

print(tensor_A.shape, tensor_B.shape)
print(tensor_A.ndim, tensor_B.ndim)

stacked_tensor = torch.cat((tensor_A, tensor_B), dim=1)
print(stacked_tensor)

torch.Size([2, 2]) torch.Size([2, 1])
2 2
tensor([[1, 2, 5],
        [3, 4, 6]])


### **Indexing (selecting data from tensors)**

In [18]:
import torch

# Create a tensor and reshape it
x = torch.arange(1, 10).reshape(1, 3, 3)

print("Original Tensor and Shape:")
print(x, x.shape)

# Print the first (and only) batch
print("\nPrint First (and Only) Batch: x[0]")
print(x[0])

# Print the first row of the first batch
print("\nPrint First Row of First Batch: x[0][0]")
print(x[0][0])

# Print the first element of the first row of the first batch
print("\nPrint First Element of First Row of First Batch: x[0][0][0]")
print(x[0][0][0])

# Print the second element of the first row of the first batch
print("\nPrint Second Element of First Row of First Batch: x[0][0][1]")
print(x[0][0][1])

# Print the third element of the second row of the first batch
print("\nPrint Third Element of Second Row of First Batch: x[0][1][2]")
print(x[0][1][2])

# Print the third element of the third row of the first batch
print("\nPrint Third Element of Third Row of First Batch: x[0][2][2]")
print(x[0][2][2])

# Print all batches, first row elements
print("\nPrint All Batches, First Row Elements: x[:, 0]")
print(x[:, 0])

# Print all batches, all rows, second column elements
print("\nPrint All Batches, All Rows, Second Column Elements: x[:, :, 1]")
print(x[:, :, 1])

# Print all batches, second row, second column element
print("\nPrint All Batches, Second Row, Second Column Element: x[:, 1, 1]")
print(x[:, 1, 1])

# Print the first (and only) batch, first row elements
print("\nPrint First (and Only) Batch, First Row Elements: x[0, 0, :]")
print(x[0, 0, :])

# Print all batches, all rows, third column elements
print("\nPrint All Batches, All Rows, Third Column Elements: x[:, :, 2]")
print(x[:, :, 2])

Original Tensor and Shape:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])

Print First (and Only) Batch: x[0]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Print First Row of First Batch: x[0][0]
tensor([1, 2, 3])

Print First Element of First Row of First Batch: x[0][0][0]
tensor(1)

Print Second Element of First Row of First Batch: x[0][0][1]
tensor(2)

Print Third Element of Second Row of First Batch: x[0][1][2]
tensor(6)

Print Third Element of Third Row of First Batch: x[0][2][2]
tensor(9)

Print All Batches, First Row Elements: x[:, 0]
tensor([[1, 2, 3]])

Print All Batches, All Rows, Second Column Elements: x[:, :, 1]
tensor([[2, 5, 8]])

Print All Batches, Second Row, Second Column Element: x[:, 1, 1]
tensor([5])

Print First (and Only) Batch, First Row Elements: x[0, 0, :]
tensor([1, 2, 3])

Print All Batches, All Rows, Third Column Elements: x[:, :, 2]
tensor([[3, 6, 9]])


In [19]:
torch.arange(1, 19).reshape(2, 1, 3, 3) # 4D Tensor

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]])

- `2` matrices (or batches)
- Each matrix has `1` channel (color channel)
- Each channel has a shape of `(3, 3)` (3 rows and 3 columns).

To calculate the total number of elements, you multiply these sizes together:
`2x1x3x3=18`


In [20]:
torch.arange(1, 55).reshape(2, 3, 3, 3) # 4D Tensor

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]],


        [[[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],

         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],

         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]]]])

## **PyTorch tensors & NumPy**

- NumPy $\rightarrow$ PyTorch tensor $\rangle$ `torch.from_numpy(ndarray)`
- PyTorch tensor $\rightarrow$ NumPy $\rangle$ `torch.Tensor.numpy()`

In [21]:
import numpy as np
import torch

# Create a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.from_numpy(numpy_array)
print(torch_tensor)
print(type(torch_tensor))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


In [22]:
import torch

# Create a PyTorch tensor
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Convert PyTorch tensor to NumPy array
numpy_array = torch_tensor.numpy()
print(numpy_array)
print(type(numpy_array))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### **device**

In [23]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Count number of devices
print(torch.cuda.device_count())

cuda
1
