- `dim = 0`, which refers to the `columns` $\downarrow$

- `dim = 1`, which refers to the `rows` $\rightarrow$

### **`torch.tensor()`**

![tensor](https://static.javatpoint.com/tutorial/pytorch/images/pytorch-tensors.png)


<br></br>

![tensor](https://editor.analyticsvidhya.com/uploads/64798tensor.png)

In [8]:
import torch

# 0-dimensional tensor (scalar)
scalar_tensor = torch.tensor(42)
print("Scalar tensor:", scalar_tensor)
print("Dimensions:", scalar_tensor.dim())

# 1-dimensional tensor (vector)
vector_tensor = torch.tensor([1, 2, 3, 4])
print("\nVector tensor:", vector_tensor)
print("Dimensions:", vector_tensor.dim())

# 2-dimensional tensor (matrix)
matrix_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("\nMatrix tensor:")
print(matrix_tensor)
print("Dimensions:", matrix_tensor.dim())

# 3-dimensional tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D tensor:")
print(tensor_3d)
print("Dimensions:", tensor_3d.dim())

# 4-dimensional tensor
tensor_4d = torch.tensor([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\n4D tensor:")
print(tensor_4d)
print("Dimensions:", tensor_4d.dim())


Scalar tensor: tensor(42)
Dimensions: 0

Vector tensor: tensor([1, 2, 3, 4])
Dimensions: 1

Matrix tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Dimensions: 2

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimensions: 3

4D tensor:
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Dimensions: 4


### **`torch.squeeze()`**

Remove dimensions of size 1 from the shape of a tensor.

In [1]:
import torch

input_tensor = torch.randn([32, 1, 28, 28], dtype=torch.float)
print("Original size:", input_tensor.size())

squeezed_tensor = torch.squeeze(input_tensor)
print("Size after squeeze:", squeezed_tensor.size())

Original size: torch.Size([32, 1, 28, 28])
Size after squeeze: torch.Size([32, 28, 28])


### **`torch.unsqueeze()`**

This function directly available in `TensorFlow`. However, in other frameworks like `PyTorch`, unsqueeze is used to add a dimension of size 1 at a specified axis. In `TensorFlow`, a similar effect can be achieved using `tf.expand_dims`.

**1. Grey Scale**

In [2]:
input_tensor = torch.randn([32, 1, 28, 28], dtype=torch.float)
print("Original size:", input_tensor.size())

first_tensor = input_tensor[0]
print("Size before unsqueeze: ",first_tensor.shape)

# unsqueeze_tensor_0 = torch.unsqueeze(x, 0)
unsqueeze_tensor_0 = first_tensor.unsqueeze(dim=0)
print("Size after unsqueeze at dim 0: ", unsqueeze_tensor_0.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_1 = first_tensor.unsqueeze(dim=1)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_1.size())

Original size: torch.Size([32, 1, 28, 28])
Size before unsqueeze:  torch.Size([1, 28, 28])
Size after unsqueeze at dim 0:  torch.Size([1, 1, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([1, 1, 28, 28])


The bottom two results are the same because both are adding a single batch dimension to a single-channel image. If first_tensor had more than one channel, the results of unsqueezing at different dimensions would be different. For example, if first_tensor was `[3, 28, 28]` (representing an `RGB` image), unsqueezing at dim 0 would result in `[1, 3, 28, 28]`, while unsqueezing at dim 1 would result in `[3, 1, 28, 28]`

**Note:** `unsqueeze_tensor_2 = x.unsqueeze(2)`

- This will raise an IndexError as we are attemptting to unsqueeze the tensor at a dimension index that doesn’t exist for the given tensor.

**2. RGB**

In [3]:
# Example: Unsqueeze a tensor
input_tensor = torch.randn([32, 3, 28, 28], dtype=torch.float)
print("Original batch size:", input_tensor.size())

first_tensor = input_tensor[0]
print("Size before unsqueeze: ", first_tensor.shape)

# unsqueeze_tensor_0 = torch.unsqueeze(x, 0)
unsqueeze_tensor_0 = first_tensor.unsqueeze(dim=0)
print("Size after unsqueeze at dim 0: ", unsqueeze_tensor_0.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_1 = first_tensor.unsqueeze(dim=1)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_1.size())

# unsqueeze_tensor_1 = torch.unsqueeze(x, 1)
unsqueeze_tensor_2 = first_tensor.unsqueeze(dim=2)
print("Size after unsqueeze at dim 1: ", unsqueeze_tensor_2.size())

Original batch size: torch.Size([32, 3, 28, 28])
Size before unsqueeze:  torch.Size([3, 28, 28])
Size after unsqueeze at dim 0:  torch.Size([1, 3, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([3, 1, 28, 28])
Size after unsqueeze at dim 1:  torch.Size([3, 28, 1, 28])


### `argmax()`

- To get the indices of the maximum values

In [7]:
import torch

# Simulated output scores from a neural network for 3 classes (cat, dog, bird)
y_pred = torch.tensor([[1.2, 0.9, 0.3, 0.4],
                       [0.2, 2.1, 1.8, 3.1],
                       [0.1, 1.5, 2.2, 2.1]])

# Applying argmax to get the indices of the maximum values along dimension
predicted_classes_0 = torch.argmax(y_pred, dim=0) # Applies argmax along dimension 0, which refers to the columns
predicted_classes_1 = torch.argmax(y_pred, dim=1) # Applies argmax along dimension 1, referring to the rows

print(predicted_classes_0)
print(predicted_classes_1)

tensor([0, 1, 2, 1])
tensor([0, 3, 2])


### **`torch.cat()`**

- Concatenating tensors along a specified dimension.

In [13]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Concatenate along dimension 0 (rows)
concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)
print("Concatenated tensor along dimension 0:\n", concatenated_tensor)

# Concatenate along dimension 1 (columns)
concatenated_tensor_dim1 = torch.cat((tensor1, tensor2), dim=1)
print("Concatenated tensor along dimension 1:\n", concatenated_tensor_dim1)

Concatenated tensor along dimension 0:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenated tensor along dimension 1:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### **`torch.flatten()`**

In [21]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Assuming concatenated_tensor_dim1 is already defined from the previous example
concatenated_tensor_dim0 = torch.cat((tensor1, tensor2), dim=0)
concatenated_tensor_dim1 = torch.cat((tensor1, tensor2), dim=1)

# Flatten the concatenated tensor
flat_tensor0 = torch.flatten(concatenated_tensor_dim0)
flat_tensor1 = torch.flatten(concatenated_tensor_dim1)

print("Flattened tensor 0:\n", flat_tensor0)
print("Flattened tensor 1:\n", flat_tensor1)

Flattened tensor 0:
 tensor([1, 2, 3, 4, 5, 6, 7, 8])
Flattened tensor 1:
 tensor([1, 2, 5, 6, 3, 4, 7, 8])


### **`torch.stack()`**

In [25]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Stack tensors along a new dimension (dimension 0)
stacked_tensor0 = torch.stack((tensor1, tensor2), dim=0)
stacked_tensor1 = torch.stack((tensor1, tensor2), dim=1)

print("Stacked tensor along dimension 0:\n", stacked_tensor0)
print("\n")
print("Stacked tensor along dimension 1:\n", stacked_tensor1)

Stacked tensor along dimension 0:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Stacked tensor along dimension 1:
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
