# **Tensor in PyTorch(Basics)**



## **Tensors**

⭕ **1D Tensor (Vector)**  
- **Example**: A list of daily temperatures.
- **Data:** `[15°C, 16°C, 18°C, ..., 12°C]`
- **Dimensionality**: `[time]`.  
- **Typical Values in TensorFlow/PyTorch**:  
  - Example: `[7]` for a week of daily temperature readings.  
  - Example: `[1000]` for 1D data with 1000 features (e.g., sensor readings).  

---

⭕ **2D Tensor (Matrix)**  
- **Example**: Grayscale image.  
- **Dimensionality**: `[height, width]`.  
- **Typical Values in TensorFlow/PyTorch**:  
  - Example: `[28, 28]` for a standard MNIST grayscale image.  
  - Example: `[512, 512]` for high-resolution grayscale images.
---

⭕ **3D Tensor**  
- **Example**: RGB Image.  
- **Dimensionality**: `[height, width, color channels]`.  
- **Typical Values in TensorFlow/PyTorch**:  
  - Example: `[224, 224, 3]` for a single color image used in models like ResNet.  
  - Example: `[64, 64, 3]` for smaller, cropped images.  

⭐**3D Tensor in NLP**:
- **Input Sentences:**
    - Hello jhon  
    - Hello alex  
    - Hello sara  

- **Vocabulary**: `["Hello", "jhon", "alex", "sara"]`.

- **One-Hot Encoding**: Each word is represented as a vector of length 4 (vocabulary size):
    - "Hello" → `[1, 0, 0, 0]`  
    - "jhon" → `[0, 1, 0, 0]`  
    - "alex" → `[0, 0, 1, 0]`  
    - "sara" → `[0, 0, 0, 1]`  

- **Tensor Shape**: `(3, 2, 4)`  
    - `3`: Number of sentences.  
    - `2`: Number of words per sentence.  
    - `4`: Vocabulary size (features for one-hot encoding).  

- **Tensor Representation**:  
    ```python
    [
        [[1, 0, 0, 0], [0, 1, 0, 0]],  # Sentence 1: "Hello jhon"
        [[1, 0, 0, 0], [0, 0, 1, 0]],  # Sentence 2: "Hello alex"
        [[1, 0, 0, 0], [0, 0, 0, 1]]   # Sentence 3: "Hello sara"
    ]
    ```

- **Chart Representation**:

| **Word**    | Hello | jhon | alex | sara |
|-------------|-------|------|------|------|
| Sentence 1  |   1   |   1  |   0  |   0  |
| Sentence 2  |   1   |   0  |   1  |   0  |
| Sentence 3  |   1   |   0  |   0  |   1  |


⭐**3D Tensor for Time Series Data: Stock Market Example**

- **Example Scenario**:
We are tracking the stock prices of **3 companies** over **7 days**, with the following features:  
    - **Open Price**  
    - **Close Price**  
    - **Volume Traded**


- **Data Representation**:
    1. **Companies (Samples)**: 3 (Company A, Company B, Company C).  
    2. **Time Steps (Days)**: 7 days.  
    3. **Features (Measurements)**: 3 (Open Price, Close Price, Volume Traded).


- **Tensor Shape**:
    - **Shape**: `(3, 7, 3)`  
        - `3`: Number of companies (samples).  
        - `7`: Number of days (time steps).  
        - `3`: Number of features (Open Price, Close Price, Volume Traded).


- **Example Tensor**:
    ```python
    [
        # Company A
        [
            [100, 105, 5000],  # Day 1: Open=100, Close=105, Volume=5000
            [102, 108, 5200],  # Day 2
            ...
            [110, 115, 5500]   # Day 7
        ],

        # Company B
        [
            [200, 210, 7000],  # Day 1
            [205, 215, 7200],  # Day 2
            ...
            [220, 230, 7500]   # Day 7
        ],

        # Company C
        [
            [300, 310, 9000],  # Day 1
            [310, 320, 9200],  # Day 2
            ...
            [330, 340, 9500]   # Day 7
        ]
    ]
    ```

---

⭕ **4D Tensor**  
- **Example**: Batch of images for machine learning, computer Vision.  
- **Dimensionality**: `[batch size, height, width, color channels]`.  
- **Typical Values in TensorFlow/PyTorch**:  
  - Example: `[32, 28, 28, 1]` for a batch of 32 grayscale MNIST images.  
  - Example: `[64, 224, 224, 3]` for a batch of 64 RGB images.  

---

⭕ **5D Tensor**  
- **Example**: Video data for machine learning.  
- **Dimensionality**: `[batch size, frames, height, width, color channels]`.  
- **Typical Values in TensorFlow/PyTorch**:  
  - Example: `[16, 10, 224, 224, 3]` for a batch of 16 videos, each with 10 frames of size `224×224` with 3 color channels.  
  - Example: `[8, 30, 64, 64, 1]` for 8 videos with 30 frames of size `64×64` in grayscale.  

---

⭕ **Summary Table**  

| **Tensor** | **Real-Life Example**             | **Dimensionality**                            | **Typical Values**                          |
|------------|-----------------------------------|-----------------------------------------------|---------------------------------------------|
| 1D         | Temperature readings over time   | `[time]`                                      | `[7]`, `[1000]`                             |
| 2D         | Grayscale image                  | `[height, width]`                             | `[28, 28]`, `[512, 512]`                    |
| 3D         | RGB image                        | `[height, width, color channels]`            | `[224, 224, 3]`, `[64, 64, 3]`             |
| 4D         | Batch of images                  | `[batch, height, width, color channels]`     | `[32, 28, 28, 1]`, `[64, 224, 224, 3]`     |
| 5D         | Video data                       | `[batch, time, height, width, color channels]`| `[16, 10, 224, 224, 3]`, `[8, 30, 64, 64, 1]`|  

In [1]:
import numpy as np

# 1D Tensor or 1D array or vector
tensor_1d = np.array([1, 2])
print("1D Tensor:\n", tensor_1d)
print("Shape:", tensor_1d.shape)
print("Size:", tensor_1d.size)
print("Number of dimensions:", tensor_1d.ndim)
print('-'*30)

# 2D Tensor
tensor_2d = np.array([[1, 2],
                      [3, 4]])
print("\n2D Tensor:\n", tensor_2d)
print("Shape:", tensor_2d.shape)
print("Size:", tensor_2d.size)
print("Number of dimensions:", tensor_2d.ndim)
print('-'*30)

# 3D Tensor
tensor_3d = np.array([[[1, 2],
                       [3, 4]],
                      [[5, 6],
                       [7, 8]]])
print("\n3D Tensor:\n", tensor_3d)
print("Shape:", tensor_3d.shape)
print("Size:", tensor_3d.size)
print("Number of dimensions:", tensor_3d.ndim)
print('-'*30)

# 4D Tensor
tensor_4d = np.array([[[[1, 2], [3, 4]],
                       [[5, 6], [7, 8]]],
                      [[[9, 10], [11, 12]],
                       [[13, 14], [15, 16]]]])
print("\n4D Tensor:\n", tensor_4d)
print("Shape:", tensor_4d.shape)
print("Size:", tensor_4d.size)
print("Number of dimensions:", tensor_4d.ndim)
print('-'*30)

# 5D Tensor
tensor_5d = np.array([[[[[1, 2], [3, 4]],
                        [[5, 6], [7, 8]]],
                       [[[9, 10], [11, 12]],
                        [[13, 14], [15, 16]]]],
                     [[[[17, 18], [19, 20]],
                       [[21, 22], [23, 24]]],
                      [[[25, 26], [27, 28]],
                       [[29, 30], [31, 32]]]]])
print("\n5D Tensor:\n", tensor_5d)
print("Shape:", tensor_5d.shape)
print("Size:", tensor_5d.size)
print("Number of dimensions:", tensor_5d.ndim)

1D Tensor:
 [1 2]
Shape: (2,)
Size: 2
Number of dimensions: 1
------------------------------

2D Tensor:
 [[1 2]
 [3 4]]
Shape: (2, 2)
Size: 4
Number of dimensions: 2
------------------------------

3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Size: 8
Number of dimensions: 3
------------------------------

4D Tensor:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Shape: (2, 2, 2, 2)
Size: 16
Number of dimensions: 4
------------------------------

5D Tensor:
 [[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[17 18]
    [19 20]]

   [[21 22]
    [23 24]]]


  [[[25 26]
    [27 28]]

   [[29 30]
    [31 32]]]]]
Shape: (2, 2, 2, 2, 2)
Size: 32
Number of dimensions: 5


⭕**Rank, Axis and Shape:**

- **Number of Axis = Rank = Number of Dimension**



⭕ **PyTorch**

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    print("GPU is available!")
    # Print the name of the GPU being used
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


The `0` in `torch.cuda.get_device_name(0)` refers to the index of the GPU device in a multi-GPU setup. In PyTorch, if you have multiple GPUs available, they are indexed starting from 0 (e.g., 0, 1, 2, etc.).

⭕**Single GPU** $\rightarrow$ If we have only one GPU, the index
 is `0`.

In [4]:
print(torch.cuda.get_device_name(0)) # Output the name of the single CPU

Tesla T4


⭕**Multiple GPUs**

In [5]:
if torch.cuda.device_count() > 1:
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i} : {torch.cuda.get_device_name(i)}")
else:
    print("Only one GPU available")

Only one GPU available


⭕**Why use different indices?**

- **Model Parallelism**: Distribute different parts of a model across multiple GPUs.
- **Data Parallelism**: Split data batches and process them in parallel on different GPUs.

**Example Use Case:**

```python
# Set a specific GPU
device = torch.device("cuda:1")  # Use GPU with index 1
model = model.to(device)        # Move the model to GPU 1

```

## **Creating a Tensor**

⭕ `torch.empty(r, c)`: It's a placeholder that reserves space in memory but doesn't have any specific values inside it.

In [6]:
# using empty
a = torch.empty(3,3)
a

tensor([[1.4013e-44, 0.0000e+00, 7.9819e-19],
        [0.0000e+00, 1.5779e-42, 0.0000e+00],
        [7.9826e-19, 0.0000e+00, 1.4013e-44]])

In [7]:
# check type
type(a)

torch.Tensor

⭕`torch.zeros(r, c)`

In [8]:
# using zeros
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

⭕`torch.ones(r, c)`

In [9]:
# using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

⭕`torch.rand(r, c)`: Generating the random tensors

⭕`torch.manual_seed(n)`

In [10]:
import torch

# Set a manual seed for reproducibility
torch.manual_seed(100)
x = torch.rand(2, 3)
x

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Reset the seed and generate the same random tensors again
torch.manual_seed(100)
x_again = torch.rand(2, 3)
x_again

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# checking the Reproducibility
torch.equal(x, x_again)

True

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

⭕`torch.tensor(r, c)`: For creating the custom tensor.

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

⭕`torch.arange(start, end, step)` - values in a range

In [15]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

⭕`torch.linspace(start, end, steps)` - evenly spaced points

In [16]:
torch.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

⭕`torch.eye(n, m=None)`: Creates a 2D identity matrix (diagonal elements are `1`, others are `0`)

In [17]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## **Tensor Shapes**

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


⭕`torch.empty_like(x)`: Creates a new tensor with the same shape and data type as `x`, but it doesn't initialize its values. The values in the new tensor will be random, uninitialized data.

In [20]:
torch.empty_like(x)

tensor([[2322206376936961119, 7310597164893758754, 3180237793526116959],
        [7020674649171501600, 8319593408446489965, 3180215807337460325]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

⚠️
```python
x = torch.tensor([[1,2,3],[4,5,6]])
torch.rand_like(x)
```

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-103-8a266f1565c3> in <cell line: 0>()
----> 1 torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'
```

> 👉Because the tensor `x` has all integers values, where as `torch.rand` generates random numbers between 0 and 1, which are floating-point values. Since a Long Tensor can only store integers, it can't hold these decimal values.

✅

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## **Tensor Data Types**

| **Data Type**         | **Dtype**         | **Description**                                                                                                                                      |
|------------------------|-------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                               |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                    |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computation.                                           |
| **BFloat16**            | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training.                                         |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained scenarios.                                    |
| **8-bit Integer**       | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                        |
| **16-bit Integer**      | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                         |
| **32-bit Integer**      | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                       |
| **64-bit Integer (Long Tensor)** | `torch.int64`     | Long integer type. Often used for large indexing arrays or tasks involving large numbers.                                                           |
| **8-bit Unsigned Integer** | `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                        |
| **Boolean**             | `torch.bool`      | Boolean type. Stores `True` or `False` values. Often used for masks in logical operations.                                                          |
| **Complex 64**          | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                    |
| **Complex 128**         | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                       |
| **Quantized Integer**   | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                   |
| **Quantized Unsigned Integer** | `torch.quint8`    | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                          |



In [24]:
# find data type
x = torch.tensor([[1,2,3],[4,5,6]])
x.dtype

torch.int64

In [25]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

⭕ **Changing the tensor data type**

In [27]:
# Create a tensor with integers
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(x.dtype)

# Convert the tensor to a different data type (float32)
y = x.to(dtype=torch.float32)
print("\nConverted Tensor:")
print(y.dtype)

Original Tensor:
torch.int64

Converted Tensor:
torch.float32


## **Mathematical operations**

### **1. Scalar operation**

In [28]:
x = torch.tensor([[1, 2], [4, 5]])
print("Original Tensor:")
print(x)

# Perform scalar operations on the tensor
print("\nAddition (x + 2):")
print(x + 2)

print("\nSubtraction (x - 2):")
print(x - 2)

print("\nMultiplication (x * 3):")
print(x * 3)

print("\nDivision (x / 2):")
print(x / 2)

print("\nInteger Division ((x * 100) // 3):")
print((x * 100) // 3)

print("\nModulo Operation (((x * 100) // 3) % 2):")
print(((x * 100) // 3) % 2)

print("\nPower (x ** 2):")
print(x ** 2)

Original Tensor:
tensor([[1, 2],
        [4, 5]])

Addition (x + 2):
tensor([[3, 4],
        [6, 7]])

Subtraction (x - 2):
tensor([[-1,  0],
        [ 2,  3]])

Multiplication (x * 3):
tensor([[ 3,  6],
        [12, 15]])

Division (x / 2):
tensor([[0.5000, 1.0000],
        [2.0000, 2.5000]])

Integer Division ((x * 100) // 3):
tensor([[ 33,  66],
        [133, 166]])

Modulo Operation (((x * 100) // 3) % 2):
tensor([[1, 0],
        [1, 0]])

Power (x ** 2):
tensor([[ 1,  4],
        [16, 25]])


### **2. Element wise operation**

In [29]:
import torch

# Define simple tensors
a = torch.tensor([[2, 4, 6], [8, 10, 12]], dtype=torch.float32)
b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

print("Tensor a:")
print(a)

print("\nTensor b:")
print(b)

# Perform element-wise operations
print("\nElement-wise Addition (a + b):")
print(a + b)

print("\nElement-wise Subtraction (a - b):")
print(a - b)

print("\nElement-wise Multiplication (a * b):")
print(a * b)

print("\nElement-wise Division (a / b):")
print(a / b)

print("\nElement-wise Power (a ** b):")
print(a ** b)

print("\nElement-wise Modulo (a % b):")
print(a % b)

Tensor a:
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

Tensor b:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Element-wise Addition (a + b):
tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])

Element-wise Subtraction (a - b):
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Element-wise Multiplication (a * b):
tensor([[ 2.,  8., 18.],
        [32., 50., 72.]])

Element-wise Division (a / b):
tensor([[2., 2., 2.],
        [2., 2., 2.]])

Element-wise Power (a ** b):
tensor([[2.0000e+00, 1.6000e+01, 2.1600e+02],
        [4.0960e+03, 1.0000e+05, 2.9860e+06]])

Element-wise Modulo (a % b):
tensor([[0., 0., 0.],
        [0., 0., 0.]])


🔷
- **`torch.abs()`**: Computes the absolute value of each element in the tensor.
- **`torch.neg()`**: Negates (flips the sign of) each element in the tensor.
- **`torch.round()`**: Rounds each element in the tensor to the nearest integer.
- **`torch.ceil()`**: Rounds each element in the tensor up to the nearest integer (ceiling).
- **`torch.floor()`**: Rounds each element in the tensor down to the nearest integer (floor).
- **`torch.clamp()`**: Limits the values in the tensor to a specified range. Values below the minimum become the minimum, and values above the maximum become the maximum.::

In [30]:
# Create tensor c with integer values
c = torch.tensor([1, -2, 3, -4])
print("original tensor:", c)

# Absolute values of c (removes negative sign)
abs_c = torch.abs(c)
print("Absolute values of c:", abs_c)

# Negation of c (negates each element's sign)
neg_c = torch.neg(c)
print("Negation of c:", neg_c)

original tensor: tensor([ 1, -2,  3, -4])
Absolute values of c: tensor([1, 2, 3, 4])
Negation of c: tensor([-1,  2, -3,  4])


In [31]:
# Create tensor d with floating-point values
d = torch.tensor([1.5, 2.4, 3.6, 4.7])
print("original tensor:", d)

# Round d to the nearest integer
rounded_d = torch.round(d)
print("Rounded d:", rounded_d)

# Apply ceil function to d (round up to the nearest integer)
ceil_d = torch.ceil(d)
print("Ceil of d:", ceil_d)

# Apply floor function to d (round down to the nearest integer)
floor_d = torch.floor(d)
print("Floor of d:", floor_d)

# Clamp d to the range [2, 3], any value below 2 becomes 2, and any value above 3 becomes 3
clamped_d = torch.clamp(d, min=2, max=3)
print("Clamped d:", clamped_d)

original tensor: tensor([1.5000, 2.4000, 3.6000, 4.7000])
Rounded d: tensor([2., 2., 4., 5.])
Ceil of d: tensor([2., 3., 4., 5.])
Floor of d: tensor([1., 2., 3., 4.])
Clamped d: tensor([2.0000, 2.4000, 3.0000, 3.0000])


### **3. Reduction operation**


In [32]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 8., 4.],
        [4., 1., 0.]])

⭕ **sum**

In [33]:
torch.sum(e)

tensor(25.)

⭕ **sum along the columns**

In [34]:
torch.sum(e, dim=0)

tensor([12.,  9.,  4.])

⭕ **sum along rows**

In [35]:
torch.sum(e, dim=1)

tensor([20.,  5.])

⭕ **mean**

In [36]:
torch.mean(e)

tensor(4.1667)

⭕ **mean along column**

In [37]:
torch.mean(e, dim=0)

tensor([6.0000, 4.5000, 2.0000])

⭕ **median**

In [38]:
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([8., 1.]),
indices=tensor([0, 1]))

⭕ **min & max**

In [39]:
torch.max(e)
torch.min(e)

tensor(0.)

⭕ **product**

In [40]:
torch.prod(e)

tensor(0.)

⭕ **Standard deviation**

In [41]:
torch.std(e)

tensor(3.3714)

⭕ **variance**

In [42]:
torch.var(e)

tensor(11.3667)

⭕ **argmax**

In [43]:
torch.argmax(e)

tensor(0)

⭕ **argmin**




In [44]:
torch.argmin(e)

tensor(5)

### **4. Matrix operations**

⭕ `matmul` & `@`

In [45]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

# matrix multiplcation
torch.matmul(f, g)

tensor([[4, 3, 8],
        [7, 4, 6]])
tensor([[0, 1],
        [9, 9],
        [8, 0]])


tensor([[91, 31],
        [84, 43]])

In [46]:
vector1 = torch.tensor([[1, 2], [3, 4]])
vector2 = torch.tensor([[1, 2], [3, 4]])

# dot product using matmul
result = torch.matmul(vector1, vector2)
print(result)

# or using the @ operator
result = vector1 @ vector2
print(result)

tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


⭕ `dot`

In [47]:
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# dot product
result = torch.dot(vector1, vector2)
print(result)

tensor(32)


⭕ `transpose`

In [48]:
# transpose
f = torch.randint(size=(2,3), low=0, high=10)
print(f)

torch.transpose(f, 0, 1)

tensor([[7, 0, 0],
        [9, 5, 7]])


tensor([[7, 9],
        [0, 5],
        [0, 7]])

⭕ `det`

$$
\text{If } A = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}, \text{ then } \det(A) = |A| =
\begin{vmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{vmatrix} =
a \begin{vmatrix}
e & f \\
h & i
\end{vmatrix} - b \begin{vmatrix}
d & f \\
g & i
\end{vmatrix} + c \begin{vmatrix}
d & e \\
g & h
\end{vmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)
$$


In [49]:
matrix_det = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(matrix_det)

# determinant
torch.det(matrix_det)

tensor([[3., 9., 4.],
        [0., 5., 7.],
        [5., 9., 9.]])


tensor(161.)

⭕ `inverse`

$$
\text{If } A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix} \text{, then, if } ad - bc \neq 0, \quad
A^{-1} = \frac{1}{ad - bc} \begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}
$$

In [50]:
m = torch.tensor([[7, 2],
                 [17, 5]], dtype=torch.float32)

inverse_matrix = torch.inverse(m)

print("Original Matrix:")
print(m)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
tensor([[ 7.,  2.],
        [17.,  5.]])

Inverse Matrix:
tensor([[  5.0000,  -2.0000],
        [-17.0000,   7.0000]])


### **5. Comparison operations**

In [51]:
# i = torch.randint(size=(2,3), low=0, high=10)
# j = torch.randint(size=(2,3), low=0, high=10)

# Creating simple tensors
i = torch.tensor([[1, 2, 3], [4, 5, 6]])
j = torch.tensor([[1, 2, 3], [3, 2, 1]])

print("Tensor i:")
print(i)
print("Tensor j:")
print(j)

# Greater than
print("i > j:")
print(i > j)

# Less than
print("i < j:")
print(i < j)

# Equal to
print("i == j:")
print(i == j)

# Not equal to
print("i != j:")
print(i != j)

# Greater than or equal to
print("i >= j:")
print(i >= j)

# Less than or equal to
print("i <= j:")
print(i <= j)

Tensor i:
tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor j:
tensor([[1, 2, 3],
        [3, 2, 1]])
i > j:
tensor([[False, False, False],
        [ True,  True,  True]])
i < j:
tensor([[False, False, False],
        [False, False, False]])
i == j:
tensor([[ True,  True,  True],
        [False, False, False]])
i != j:
tensor([[False, False, False],
        [ True,  True,  True]])
i >= j:
tensor([[True, True, True],
        [True, True, True]])
i <= j:
tensor([[ True,  True,  True],
        [False, False, False]])


### **6. Special functions**

- **Logarithm**: $ \text{torch.log}(x) = \ln(x) $ (Natural logarithm of $x$)  
- **Exponential**: $ \text{torch.exp}(x) = e^x $ (Exponential of $x$)  
- **Square Root**: $ \text{torch.sqrt}(x) = \sqrt{x} $ (Square root of $x$)  
- **Sigmoid**: $ \text{torch.sigmoid}(x) = \frac{1}{1 + e^{-x}} $ (S-shaped activation function)  
- **Softmax**: $ \text{torch.softmax}(x_i) = \frac{e^{x_i}}{\sum_{j} e^{x_j}} $ (Converts logits to probabilities)  
- **ReLU (Rectified Linear Unit)**: $ \text{torch.relu}(x) = \max(0, x) $ (Keeps positive values, sets negative to 0)  


In [52]:
# Creating a simple tensor
k = torch.tensor([[1, 2, 3], [4, -5, -6]], dtype=torch.float32)

# Display the tensor
print("Original Tensor (k):")
print(k)
print()

# Logarithm
print("Logarithm (torch.log):")
print(torch.log(k))  # Natural logarithm
print()

# Exponential
print("Exponential (torch.exp):")
print(torch.exp(k))  # e^x
print()

# Square Root
print("Square Root (torch.sqrt):")
print(torch.sqrt(k))  # √x
print()

# Sigmoid
print("Sigmoid (torch.sigmoid):")
print(torch.sigmoid(k))  # 1 / (1 + e^(-x))
print()

# Softmax (along dimension 0)
print("Softmax along dimension 0 (torch.softmax):")
print(torch.softmax(k, dim=0))  # Converts logits to probabilities along dim=0 (Columns)
print()

# Softmax (along dimension 1)
print("Softmax along dimension 1 (torch.softmax):")
print(torch.softmax(k, dim=1))  # Converts logits to probabilities along dim=1 (Rows)
print()

# ReLU (Rectified Linear Unit)
print("ReLU (torch.relu):")
print(torch.relu(k))  # ReLU operation (max(0, x))
print()

Original Tensor (k):
tensor([[ 1.,  2.,  3.],
        [ 4., -5., -6.]])

Logarithm (torch.log):
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863,    nan,    nan]])

Exponential (torch.exp):
tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 6.7379e-03, 2.4788e-03]])

Square Root (torch.sqrt):
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000,    nan,    nan]])

Sigmoid (torch.sigmoid):
tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.0067, 0.0025]])

Softmax along dimension 0 (torch.softmax):
tensor([[4.7426e-02, 9.9909e-01, 9.9988e-01],
        [9.5257e-01, 9.1105e-04, 1.2339e-04]])

Softmax along dimension 1 (torch.softmax):
tensor([[9.0031e-02, 2.4473e-01, 6.6524e-01],
        [9.9983e-01, 1.2339e-04, 4.5392e-05]])

ReLU (torch.relu):
tensor([[1., 2., 3.],
        [4., 0., 0.]])



## Inplace Operations

In PyTorch, methods with a trailing underscore (e.g., `add_`, `relu_`) perform **in-place operations**. This means they modify the original tensor's data directly instead of creating a new tensor.

In [53]:
x = torch.tensor([1.0, 2.0, 3.0])

x.add_(5)  # Adds 5 to each element of x, modifying x in place
print(x)

tensor([6., 7., 8.])


In [54]:
x = torch.tensor([-1.0, 0.0, 2.0])

x.relu_() # Applies ReLU in place
print(x)

tensor([0., 0., 2.])


In [55]:
# Define two tensors
m = torch.tensor([1, 2, 3])
n = torch.tensor([3, 2, 1])

# Display the original tensors
print("Initial Tensor m: ", m)
print("Initial Tensor n: ", n)

# Perform in-place addition
m.add_(n)

# Display the results
print("\nTensro m after in-place addition: ", m)
print("Tensor n remains unchanged:", n)

Initial Tensor m:  tensor([1, 2, 3])
Initial Tensor n:  tensor([3, 2, 1])

Tensro m after in-place addition:  tensor([4, 4, 4])
Tensor n remains unchanged: tensor([3, 2, 1])


In [56]:
# Define a tensor
tensor = torch.tensor([-1, 2, -3, 4, -5], dtype=torch.float)

# Display the original tensor
print("Initial Tensor: ", tensor)

# Perform in-place ReLU operation
tensor.relu_()

# Display the results
print("\nTensor after in-place ReLU operation: ", tensor)

Initial Tensor:  tensor([-1.,  2., -3.,  4., -5.])

Tensor after in-place ReLU operation:  tensor([0., 2., 0., 4., 0.])


## **Copying a Tensor**

**what it is the problem with the asignent ooperater thiat is `a=b`?**

When you use the assignment operator `a = b` in Python, it doesn't create a new copy of the data. Instead, it makes `a` and `b` point to the same object in memory. This means that any changes made to `a` will also affect `b`, and vice versa. This can lead to unintended side effects if you're not careful.

In [57]:
import torch

# Creating a tensor
a = torch.tensor([1, 2, 3])
print("Befor the assignement operation Tensor `a`: ", a)

b = a

# Modifying the assigned tensor
a[0] = 0

print("Original Tensor a :", a)
print("Assigned Tensor b :", b)

print("ID of a: ", id(a))
print("ID of b: ", id(b))

print(id(a)==id(b))

Befor the assignement operation Tensor `a`:  tensor([1, 2, 3])
Original Tensor a : tensor([0, 2, 3])
Assigned Tensor b : tensor([0, 2, 3])
ID of a:  133717964615856
ID of b:  133717964615856
True


In [58]:
a = torch.rand(2,3)
b = a
a[0][0] = 0

print(a)
print(b)

print("ID of a: ", id(a))
print("ID of b: ", id(b))

print(id(a)==id(b))

tensor([[0.0000, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])
tensor([[0.0000, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])
ID of a:  133717964615952
ID of b:  133717964615952
True


⭕ `clone()`

- `a.clone()` method is used to create a copy of a tensor `a`. This is particularly useful when you want to modify a tensor without affecting the original one. **For example**, if you want to perform operations on a tensor but keep the original tensor unchanged, you can use `a.clone()` to create a separate copy.

In [59]:
a = torch.tensor([1, 2, 3])
b = a.clone()

a[0] = 10

print(a)
print(b)

print("ID of a: ", id(a))
print("ID of b: ", id(b))

print(id(a)==id(b))

tensor([10,  2,  3])
tensor([1, 2, 3])
ID of a:  133717964616048
ID of b:  133717964615664
False


## **Tensor operations on GPU**

In [60]:
import torch

# Check if CUDA is available on the system
print(torch.cuda.is_available())

True


This code sets the device to GPU for PyTorch operations. The `torch.device("cuda")` command specifies that the computations should be performed on a CUDA-enabled GPU, which can significantly speed up the processing.

In [61]:
device = torch.device("cuda")

# Creating the tensor on GPU's VRAM
tensor = torch.rand((2, 3), device=device)

print(tensor)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')


In [62]:
tensor = torch.rand(2, 3)
print(a) # this tenosr exist on CPU

# Moving the existing tensor to GPU
b = a.to(device)
print(b)

tensor([10,  2,  3])
tensor([10,  2,  3], device='cuda:0')


In [63]:
import torch
import time

# Define the size of the matrix
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure the time for matrix multiplication on CPU
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
end_time_cpu = time.time()
cpu_time = end_time_cpu - start_time_cpu
print(f"Time on CPU: {cpu_time:.4f} sec")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# Synchronize to ensure all GPU operations are complete before starting the timer
torch.cuda.synchronize()

# Measure the time for matrix multiplication on GPU
start_time_gpu = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU

# Synchronize to ensure all GPU operations are complete
torch.cuda.synchronize()
end_time_gpu = time.time()
gpu_time = end_time_gpu - start_time_gpu
print(f"Time on GPU: {gpu_time:.4f} sec")

# Compare results
print(f"\nSpeedUp (CPU time / GPU time): {cpu_time / gpu_time:.2f}")

Time on CPU: 17.9147 sec
Time on GPU: 0.6942 sec

SpeedUp (CPU time / GPU time): 25.81



⭕`torch.cuda.synchronize()` makes sure that all tasks running on the GPU are completely finished before the program moves on. This is important when measuring how long a GPU operation takes.

If you don’t use it, the program might only measure the time it takes to *send* the task to the GPU, not the time the GPU actually spends doing the work. This can give you incorrect or misleading results about the operation’s speed.

## **Reshaping Tensors**

### ✅**Example 1:** Flatten a 2D tensor into 1D

In [64]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # (2, 3)

y = x.reshape(-1)
print(y)         # tensor([1, 2, 3, 4, 5, 6])
print(y.shape)   # torch.Size([6])

torch.Size([2, 3])
tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


### ✅**Example 2:** Convert 1D tensor into 2D `column` vector

In [65]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)  # (4,)

y = x.reshape(-1, 1)
print(y)
# tensor([[1],
#         [2],
#         [3],
#         [4]])
print(y.shape)  # torch.Size([4, 1])

torch.Size([4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


### ✅**Example 3:** Convert 1D tensor into 2D `row` vector

In [66]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)  # (4,)

y = x.reshape(1, -1)
print(y)

# tensor([[1, 2, 3, 4]])
print(y.shape)  # torch.Size([1, 4])

torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


### ✅**Example 4:** 3D reshape

In [67]:
x = torch.arange(24)  # tensor([0, 1, ..., 23])
y = x.reshape(2, 3, 4)

print(y)
print(y.shape)  # torch.Size([2, 3, 4])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


⭕ `reshape()`

In [70]:
import torch

a = torch.ones(4, 4)
print(a, a.shape)

# Reshaping the Tensor
b = a.reshape(2, 2, 2, 2)
print(b, b.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.Size([4, 4])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]]) torch.Size([2, 2, 2, 2])


⭕ `flatten()`

In [71]:
a = torch.ones(4, 4)
b = a.flatten()

print(b, b.shape)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([16])


⭕ `permute()`: The permute function in PyTorch is used to rearrange the dimensions of a tensor.

In [72]:
import torch

# Create a 3D tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]],
                       [[7, 8, 9], [10, 11, 12]]])

print("Original tensor shape:", tensor.shape)
print("Original tensor:\n", tensor)

# Permute the dimensions
permuted_tensor1 = tensor.permute(2, 0, 1)
permuted_tensor2 = tensor.permute(2, 1, 0)

print("\nPermuted tensor shape:", permuted_tensor1.shape)
print("Permuted tensor:\n", permuted_tensor1)

print("\nPermuted tensor shape:", permuted_tensor2.shape)
print("Permuted tensor:\n", permuted_tensor2)

Original tensor shape: torch.Size([2, 2, 3])
Original tensor:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

Permuted tensor shape: torch.Size([3, 2, 2])
Permuted tensor:
 tensor([[[ 1,  4],
         [ 7, 10]],

        [[ 2,  5],
         [ 8, 11]],

        [[ 3,  6],
         [ 9, 12]]])

Permuted tensor shape: torch.Size([3, 2, 2])
Permuted tensor:
 tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]])


⭕`unsqueeze`: The unsqueeze function in PyTorch is used to add a dimension of size 1 at a specified position. This can be useful for aligning tensors with different shapes

In [73]:
import torch

# Create a simple 2D tensor
t = torch.tensor([[1, 2], [3, 4]])

# Print the tensor and its shape
print(t, t.shape)

# Unsqueeze to add a dimension at position 0
print("\n", t.unsqueeze(0), t.unsqueeze(0).shape)
# Unsqueeze to add a dimension at position 1
print("\n", t.unsqueeze(1), t.unsqueeze(1).shape)
# Unsqueeze to add a dimension at position 2
print("\n", t.unsqueeze(2), t.unsqueeze(2).shape)

tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])

 tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])

 tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])

 tensor([[[1],
         [2]],

        [[3],
         [4]]]) torch.Size([2, 2, 1])


In [74]:
import torch

# Create a 3D tensor
t = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print the tensor and its shape
print(t, t.shape)

# Unsqueeze to add a dimension at position 0
print("\n", t.unsqueeze(0), t.unsqueeze(0).shape)
# Unsqueeze to add a dimension at position 1
print("\n", t.unsqueeze(1), t.unsqueeze(1).shape)
# Unsqueeze to add a dimension at position 2
print("\n", t.unsqueeze(2), t.unsqueeze(2).shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])

 tensor([[[[1, 2],
          [3, 4]],

         [[5, 6],
          [7, 8]]]]) torch.Size([1, 2, 2, 2])

 tensor([[[[1, 2],
          [3, 4]]],


        [[[5, 6],
          [7, 8]]]]) torch.Size([2, 1, 2, 2])

 tensor([[[[1, 2]],

         [[3, 4]]],


        [[[5, 6]],

         [[7, 8]]]]) torch.Size([2, 2, 1, 2])


In [75]:
import torch

# unsqueeze image size
i = torch.rand(226, 226, 3)

# Print the tensor shapes
print("Original tensor shape:",i.shape)
print("\nShape after unsqueeze(0):", i.unsqueeze(0).shape)
print("\nShape after unsqueeze(1):", i.unsqueeze(1).shape)
print("\nShape after unsqueeze(2):", i.unsqueeze(2).shape)


Original tensor shape: torch.Size([226, 226, 3])

Shape after unsqueeze(0): torch.Size([1, 226, 226, 3])

Shape after unsqueeze(1): torch.Size([226, 1, 226, 3])

Shape after unsqueeze(2): torch.Size([226, 226, 1, 3])


⭕`squeeze`: this operation removes dimensions with size 1 from the tensor.

In [76]:
import torch

# Create a simple 3D tensor with a size of 1 in one of the dimensions
t = torch.tensor([[[1, 2]], [[3, 4]]])

# Print the tensor and its shape
# Squeeze to remove dimensions with size 1
print(t, t.shape)
print("\n", t.squeeze(0), t.squeeze(0).shape)
print("\n", t.squeeze(1), t.squeeze(1).shape)
print("\n", t.squeeze(2), t.squeeze(2).shape)

tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])

 tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])

 tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])

 tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])


In [77]:
import torch

# Create a 2D tensor
t = torch.tensor([[1, 2], [3, 4], [5, 6]])  # Shape will be (3, 2)
print(t, t.shape)

# Add a dimension with size 1
t = t.unsqueeze(1)                          # Shape becomes (3, 1, 2)

# Print the tensor and its shape
print("\n", t, t.shape)

# Squeeze to remove dimensions with size 1
print("\n", t.squeeze(1), t.squeeze(1).shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])

 tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]]) torch.Size([3, 1, 2])

 tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])


In [78]:
d = torch.rand(1, 4)

print(d)
print("\n", d.squeeze(0))
print("\n", d.shape, d.squeeze(0).shape)

tensor([[0.3316, 0.6414, 0.1981, 0.7998]])

 tensor([0.3316, 0.6414, 0.1981, 0.7998])

 torch.Size([1, 4]) torch.Size([4])


In [79]:
d = torch.rand(1, 2, 2)

print(d)
print("\n", d.squeeze(0))
print("\n", d.shape, d.squeeze(0).shape)

tensor([[[0.5949, 0.4458],
         [0.2918, 0.5932]]])

 tensor([[0.5949, 0.4458],
        [0.2918, 0.5932]])

 torch.Size([1, 2, 2]) torch.Size([2, 2])


In [80]:
d = torch.rand(1, 2, 3)

print(d)
print("\n", d.squeeze(0))
print("\n", d.shape, d.squeeze(0).shape)

tensor([[[0.6257, 0.5635, 0.4637],
         [0.1684, 0.2545, 0.2938]]])

 tensor([[0.6257, 0.5635, 0.4637],
        [0.1684, 0.2545, 0.2938]])

 torch.Size([1, 2, 3]) torch.Size([2, 3])


In [81]:
d = torch.rand(1, 2, 2, 2)

print(d)
print("\n", d.squeeze(0))
print("\n", d.shape, d.squeeze(0).shape)

tensor([[[[0.6345, 0.8546],
          [0.8584, 0.6476]],

         [[0.5805, 0.8800],
          [0.7746, 0.4605]]]])

 tensor([[[0.6345, 0.8546],
         [0.8584, 0.6476]],

        [[0.5805, 0.8800],
         [0.7746, 0.4605]]])

 torch.Size([1, 2, 2, 2]) torch.Size([2, 2, 2])


## **Numpy $\rightarrow$ PyTorch**

In [82]:
import torch
import numpy as np

# Create a NumPy array
np_array = np.array([1, 2])

# Convert to PyTorch tensor
tensor = torch.from_numpy(np_array)

# Print NumPy array and its type
print("NumPy Array:")
print(np_array, "Type:", type(np_array))

# Print PyTorch tensor and its type
print("\nPyTorch Tensor:")
print(tensor, "Type:", type(tensor))

# Convert back to NumPy array
np_array_back = tensor.numpy()

# Print converted NumPy array and its type
print("\nConverted Back to NumPy Array:")
print(np_array_back, "Type:", type(np_array_back))

NumPy Array:
[1 2] Type: <class 'numpy.ndarray'>

PyTorch Tensor:
tensor([1, 2]) Type: <class 'torch.Tensor'>

Converted Back to NumPy Array:
[1 2] Type: <class 'numpy.ndarray'>


⚠️ **Device**: If the tensor is on a GPU (i.e., `torch.Tensor.cuda()`), you need to move it to the CPU first before calling `.numpy()`. You can do this using `.cpu()`:

```python
torch_tensor = torch_tensor.cuda()  # Example with a GPU tensor
np_array = torch_tensor.cpu().numpy()

```

## **view**

`.view()` and `.reshape()` are used to change the shape of tensors, but there are some important differences between them. Here's a clear explanation:


🔍 `view()`
- **Purpose**: Returns a new tensor with the same data but a different shape.
- **Key Requirement**: The tensor must be contiguous in memory.
- **Performance**: Fast, as it doesn’t copy data (just creates a new view).
- **Error**: Will raise an error if the tensor is not contiguous.

In [84]:
x = torch.randn(2, 3)
x_view = x.view(3, 2)  # OK if x is contiguous

print(x)
print(x_view)

tensor([[ 0.4317, -0.3443,  0.1213],
        [-0.4772, -0.0543, -0.6680]])
tensor([[ 0.4317, -0.3443],
        [ 0.1213, -0.4772],
        [-0.0543, -0.6680]])


> If `x` is not contiguous (e.g., `after.transpose()`), `x.view(...)` will raise an error.

In [86]:
x = torch.randn(2, 3)
x_reshape = x.reshape(3, 2)  # Always works

print(x)
print(x_reshape)

tensor([[ 0.0171, -0.4359, -0.0984],
        [ 1.4533, -0.2765,  0.8185]])
tensor([[ 0.0171, -0.4359],
        [-0.0984,  1.4533],
        [-0.2765,  0.8185]])


**🤔 When to Use Which**

| Situation                   | Use `.view()`             | Use `.reshape()`             |
| --------------------------- | ------------------------- | ---------------------------- |
| Tensor is contiguous        | ✅ Preferred (faster)      | ✅ Works, but may be overkill |
| Tensor is not contiguous    | ❌ Raises error            | ✅ Works                      |
| You want guaranteed success | ❌ Might fail              | ✅ Safe choice                |
| Performance critical code   | ✅ If tensor is contiguous | ❌ Might copy, less efficient |
